# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-15 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Organisation', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Mob', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=100)),
                ('Membership', models.CharField(max_length=100)),
                ('DD', models.CharField(blank=True, max_length=100)),
                ('Amount', models.CharField(blank=True, max_length=100)),
                ('Bank', models.CharField(blank=True, max_length=15)),
                ('Branch', models.CharField(blank=True, max_length=100)),
                ('Date', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
